version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv run jupyter-book build single-decision-making/
    - mkdir -p _readthedocs && cp -r ./single-decision-making/_build/html _readthedocs/.
