name: deploy-sdm

on:
  push:
    branches:
    - main
    paths:
    - ai-notes/**

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install uv package manager
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.19"

    - name: Build the book
      run: |
        jupyter-book build ai-notes 

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "ai-notes/_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
