name: deploy-notes

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv package manager
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.19" 

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build the book
      run: |
        uv run jupyter-book build ai-notes 

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "ai-notes/_build/html"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
